version: '3'

services:
  
  database: 
    build: .\C:\users\feder\desktop\microservicesprojectits\clientidb
    networks:
      - connessioneclienti

  api: 
    image: .\C:\users\feder\desktop\microservicesprojectits\clientiapi
    ports:
      - "8080:80"
    networks:
      - connessioneclienti

networks:
  connessioneclienti: 
    driver: bridge

