version: '3'

services:
  database:
    build: .\ClientiDB
    environment:
      POSTGRES_DB: ClientiDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    container_name: "clientidata"
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    build: .\ClientiAPI
    ports:
      - "80:5000"
    container_name: "apiclienti"
    depends_on: 
      - database
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
