version: '3'

services:
  database:
    build: .\ClientiDB
    environment:
      POSTGRES_DB: ClientiDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2

  api:
    build: .\ClientiAPI
    ports:
      - "5040:5040"
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3

networks:
  mynetwork:
    driver: default
    config:
        - subnet: 172.18.0.0/16
