version: '3'

services:
  database:
    build: .\microservicesprojectits\UserDB
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork

  api:
    build: .\microservicesprojectits\clientiapi
    ports:
      - "8080:80"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
