version: '3'

services:
  database:
    build: .\ClientiDB
    environment:
      POSTGRES_DB: ClientiDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  api:
    build: .\ClientiAPI
    ports:
      - "5040:5040"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
