version: '3'

services:
  clientidata:
    build: .\ClientiDB
    environment:
      POSTGRES_DB: ClientiDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    container_name: "clientidata"

  apiclienti:
    build: .\ClientiAPI
    ports:
      - "5000:5000"
    container_name: "apiclienti"
    image: nerifede/microservicesprojectsits:Apiclienti
    depends_on: 
      - clientidata
    networks:
      - mynetwork

  libridata:
    build: .\LibriDB
    environment:
      POSTGRES_DB: LibriDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork
    container_name: "libridata"

  apilibri:
    build: .\LibriAPI
    ports:
      - "4999:4999"
    container_name: "apilibri"
    image: nerifede/microservicesprojectsits:Apilibri
    depends_on: 
      - libridata
    networks:
      - mynetwork

  prestitidata:
    build: .\PrestitiDB
    environment:
      POSTGRES_DB: PrestitiDB
      POSTGRES_USER: fede
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork
    container_name: "prestitidata"

  apiprestiti:
    build: .\PrestitiAPI
    ports:
      - "4998:4998"
    container_name: "apiprestiti"
    image: nerifede/microservicesprojectits:Apiprestiti
    depends_on: 
      - prestitidata
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
